DROP DATABASE if EXISTS dbLeagueOfYourLegends;
CREATE DATABASE if NOT exists dbLeagueOfYourLegends;
USE dbLeagueOfYourLegends;

# TABELA FEITIÇOS
CREATE TABLE tbSpell(
	idSpell smallint primary key auto_increment,
    nomSpell varchar(16) not null,
    imgSpell varchar(24) not null
);

INSERT INTO tbSpell(nomSpell, imgSpell)
	values ('Curar', 'SummonerHeal'),
		   ('Fantasma', 'SummonerHaste'),
		   ('Barreira', 'SummonerBarrier'),
		   ('Exaustão', 'SummonerExhaust'),
		   ('Flash', 'SummonerFlash'),
		   ('Teleporte', 'SummonerTeleport'),
		   ('Golpear', 'SummonerSmite'),
		   ('Purificar', 'SummonerBoost'),
		   ('Incendiar', 'SummonerDot');
           
# TABELA PAR DE FEITIÇOS PARA CAMPEÃO
CREATE TABLE tbPairSpells(
	idPairSpells smallint primary key auto_increment,
    idPrimSpell smallint not null,
    idSecSpell smallint not null,
    
    foreign key(idPrimSpell) references tbSpell(idSpell),
    foreign key(idSecSpell) references tbSpell(idSpell)
);

# TABELA ITENS
CREATE TABLE tbItem(
	idItem smallint primary key auto_increment,
    nomItem varchar(48) not null,
    imgItem smallint not null
);

INSERT INTO tbItem(nomItem, imgItem)
	values  ('Botas', '1001'),
			('Amuleto da Fada', '1004'),
			('Pérola do Rejuvenescimento', '1006'),
			('Cinto do Gigante', '1011'),
			('Capa da Agilidade', '1018'),
			('Varinha Explosiva', '1026'),
			('Cristal de Safira', '1027'),
			('Cristal de Rubi', '1028'),
			('Couraça de Pano', '1029'),
			('Cota de Malha', '1031'),
			('Manto Anula-Magia', '1033'),
			('Lâmina Cálida', '1035'),
			('Espada Longa', '1036'),
			('Picareta', '1037'),
			('Espada G. p. C.', '1038'),
			('Lâmina Álgida', '1039'),
			('Lâmina de Obsidiana', '1040'),
			('Adaga', '1042'),
			('Arco Recurvo', '1043'),
			('Tomo Amplificador', '1052'),
			('Cetro Vampírico', '1053'),
			('Escudo de Doran', '1054'),
			('Lâmina de Doran', '1055'),
			('Anel de Doran', '1056'),
			('Capa Negatron', '1057'),
			('Bastão Desnecessariamente Grande', '1058'),
			('Lacre Sombrio', '1082'),
			('Abatedora', '1083'),
			('Projétil Perfurante', '1500'),
			('Fortificação', '1501'),
			('Armadura Reforçada', '1502'),
			('Olho do Vigia', '1503'),
			('Vanguarda', '1504'),
			('Bastão Eletrizante', '1505'),
			('Armadura Reforçada', '1506'),
			('Sobrecarga', '1507'),
			('Meias Antitorre', '1508'),
			('Entusiasmo', '1509'),
			('Entusiasmo Sem Noção', '1510'),
			('Armadura Super Mech', '1511'),
			('Campo de Força Super Mech', '1512'),
			('Barricada da Torre', '1515'),
			('Recompensa de estrutura', '1516'),
			('Recompensa de estrutura', '1517'),
			('Recompensa de estrutura', '1518'),
			('Recompensa de estrutura', '1519'),
			('Poção de Vida', '2003'),
			('Biscoito Total da Determinação Eterna', '2010'),
			('Estilhaço de Kircheis', '2015'),
			('Poção com Refil', '2031'),
			('Poção Corrupta', '2033'),
			('Berrante do Guardião', '2051'),
			('Poritos', '2052'),
			('Sentinela de Controle', '2055'),
			('Hino Bélico de Shurelya', '2065'),
			('Elixir de Ferro', '2138'),
			('Elixir da Feitiçaria', '2139'),
			('Elixir da Ira', '2140'),
			('Pulverizador de Tropas', '2403'),
			('Cronômetro Inicial', '2419'),
			('Cronômetro', '2420'),
			('Cronômetro Quebrado', '2421'),
			('Botas Levemente Mágicas', '2422'),
			('Cronômetro Perfeitamente Calculado', '2423'),
			('Cronômetro Quebrado', '2424'),
			('Proteção Imutável', '3001'),
			('Cajado do Arcanjo', '3003'),
			('Manamune', '3004'),
			('Grevas do Berserker', '3006'),
			('Botas da Rapidez', '3009'),
			('Putrificador Quimtec', '3011'),
			('Sapatos do Feiticeiro', '3020'),
			('Broquel Glacial', '3024'),
			('Anjo Guardião', '3026'),
			('Gume do Infinito', '3031'),
			('Lembrete Mortal', '3033'),
			('Último Sussurro', '3035'),
			('Lembranças do Lorde Dominik', '3036'),
			('Abraço de Seraph', '3040'),
			('Ladrão de Almas de Mejai', '3041'),
			('Muramana', '3042'),
			('Fago', '3044'),
			('Dançarina Fantasma', '3046'),
			('Botas Galvanizadas de Aço', '3047'),
			('Convergência de Zeke', '3050'),
			('Machado Termestre', '3051'),
			('Sinal de Sterak', '3053'),
			('Fulgor', '3057'),
			('Semblante Espiritual', '3065'),
			('Couraça Lunar Alada', '3066'),
			('Gema Ardente', '3067'),
			('Égide de Fogo Solar', '3068'),
			('Lágrima da Deusa', '3070'),
			('Cutelo Negro', '3071'),
			('Sedenta por Sangue', '3072'),
			('Hidra Raivosa', '3074'),
			('Armadura de Espinhos', '3075'),
			('Colete Espinhoso', '3076'),
			('Tiamat', '3077'),
			('Força da Trindade', '3078'),
			('Carapaça do Vigia', '3082'),
			('Armadura de Warmog', '3083'),
			('Furacão de Runaan', '3085'),
			('Zelo', '3086'),
			('Capuz da Morte de Rabadon', '3089'),
			('Limite da Razão', '3091'),
			('Canhão Fumegante', '3094'),
			('Chuva de Canivete', '3095'),
			('Perdição de Lich', '3100'),
			('Véu da Banshee', '3102'),
			('Égide da Legião', '3105'),
			('Redenção', '3107'),
			('Códex Demoníaco', '3108'),
			('Juramento do Cavaleiro', '3109'),
			('Coração Congelado', '3110'),
			('Passos de Mercúrio', '3111'),
			('Orbe do Guardião', '3112'),
			('Cintilação Etérea', '3113'),
			('Ídolo Proibido', '3114'),
			('Dente de Na\'Shor', '3115'),
			('Cetro de Cristal de Rylai', '3116'),
			('Botas da Mobilidade', '3117'),
			('Aproximação Invernal', '3119'),
			('Fimbulwinter', '3121'),
			('Chamado do Carrasco', '3123'),
			('Lâmina da Fúria de Guinsoo', '3124'),
			('Martelo de Guerra de Caulfield', '3133'),
			('Punhal Serrilhado', '3134'),
			('Cajado do Vazio', '3135'),
			('Cimitarra Mercurial', '3139'),
			('Bandana de Mercúrio', '3140'),
			('Lâmina Fantasma de Youmuu', '3142'),
			('Presságio de Randuin', '3143'),
			('Alternador Hextec', '3145'),
			('Explocinturão Hextec', '3152'),
			('Espada do Rei Destruído', '3153'),
			('Hexdrinker', '3155'),
			('Mandíbula de Malmortius', '3156'),
			('Ampulheta de Zhonya', '3157'),
			('Botas Ionianas da Lucidez', '3158'),
			('Morellonomicon', '3165'),
			('Lâmina do Guardião', '3177'),
			('Glaive Sombria', '3179'),
			('Quebracascos', '3181'),
			('Martelo do Guardião', '3184'),
			('Medalhão dos Solari de Ferro', '3190'),
			('Armaguarda da Caçadora', '3191'),
			('Placa Gargolítica', '3193'),
			('Capuz do Espectro', '3211'),
			('Bênção de Mikael', '3222'),
			('Efígie do Espantalho', '3330'),
			('Sentinela Invisível', '3340'),
			('Alteração Vidente', '3363'),
			('Lente do Oráculo', '3364'),
			('Sua Parte', '3400'),
			('Turíbulo Ardente', '3504'),
			('Colhedor de Essência', '3508'),
			('Olho do Arauto', '3513'),
			('Lança Negra da Kalista', '3599'),
			('Lança Negra da Kalista', '3600'),
			('Couraça do Defunto', '3742'),
			('Hidra Titânica', '3748'),
			('Braçadeira Cristalina', '3801'),
			('Capítulo Perdido', '3802'),
			('Limiar da Noite', '3814'),
			('Gume do Ladrão Arcano', '3850'),
			('Presas Gélidas', '3851'),
			('Estilhaço de Gelo Verdadeiro', '3853'),
			('Guarda-ombros de Aço', '3854'),
			('Espaldeiras de Aço Rúnico', '3855'),
			('Ombreiras de Pedralva', '3857'),
			('Escudo Relicário', '3858'),
			('Broquel de Targon', '3859'),
			('Bastião da Montanha', '3860'),
			('Foice Espectral', '3862'),
			('Tormento Crescente', '3863'),
			('Foice da Névoa Negra', '3864'),
			('Orbe do Oblívio', '3916'),
			('Mandato Imperial', '4005'),
			('Força da Natureza', '4401'),
			('A Espátula Dourada', '4403'),
			('Foco do Horizonte', '4628'),
			('Ímpeto Cósmico', '4629'),
			('Joia da Ruína', '4630'),
			('Barreira Verdejante', '4632'),
			('Criafendas', '4633'),
			('Olhar Sanguessuga', '4635'),
			('Colhedor Noturno', '4636'),
			('Abraço Demoníaco', '4637'),
			('Pedra-vigia Observadora', '4638'),
			('Pedra-vigia Inspiradora', '4641'),
			('Espelho de Bandópolis', '4642'),
			('Pedra-vigia Vigilante', '4643'),
			('Coroa da Rainha Despedaçada', '4644'),
			('Chama Sombria', '4645'),
			('Chicote Ferrifarpo', '6029'),
			('Alvorada de Pratânia', '6035'),
			('Dança da Morte', '6333'),
			('Serrespada Quimiopunk', '6609'),
			('Cajado Aquafluxo', '6616'),
			('Regenerador de Pedra Lunar', '6617'),
			('Hemodrenário', '6630'),
			('Quebrapassos', '6631'),
			('Ruptor Divino', '6632'),
			('Angústia de Liandry', '6653'),
			('Tormenta de Luden', '6655'),
			('Glacieterno', '6656'),
			('Brasa de Bami', '6660'),
			('Manopla do Raio de Gelo', '6662'),
			('Quimiotanque Turbo', '6664'),
			('Aljava Vespertina', '6670'),
			('Força do Vendaval', '6671'),
			('Mata-Cráquens', '6672'),
			('Arco-escudo Imortal', '6673'),
			('Adagas Rápidas Navori', '6675'),
			('A Coletora', '6676'),
			('Faca da Fúria', '6677'),
			('Crepúsculo de Draktharr', '6691'),
			('Eclipse', '6692'),
			('Garra do Espreitador', '6693'),
			('Rancor de Serylda', '6694'),
			('Presa da Serpente', '6695'),
			('Arco do Axioma', '6696'),
			('Garra da Ave de Areia', '7000'),
			('Sizígia', '7001'),
			('Escultor Sombrio de Draktharr', '7002'),
			('Hexperimento Turbocarregado', '7003'),
			('Insígnia da Fornalha', '7004'),
			('Sufocamento Gélido', '7005'),
			('Tufão', '7006'),
			('Sacrifício da Serpente', '7007'),
			('Sentinela Sanguinária', '7008'),
			('Maldição de Icathia', '7009'),
			('Vesperal', '7010'),
			('Aeropropulsor Aprimorado', '7011'),
			('Lamento de Liandry', '7012'),
			('Olho de Luden', '7013'),
			('Inverno Eterno', '7014'),
			('Fome Incessante', '7015'),
			('Assolador de Sonhos', '7016'),
			('Deicídio', '7017'),
			('Força do Infinito', '7018'),
			('Relicário do Alvorecer Dourado', '7019'),
			('Réquiem de Shurelya', '7020'),
			('Conjurador Estelar', '7021'),
			('Centro de Comando', '7022'),
			('Equinócio', '7023'),
			('Cesura', '7024'),
			('Gangplank Placeholder', '7050'),
			('Correntes de Anátema', '8001'),
			('Máscara Abissal', '8020');

# TABELA BUILD INICIAL
CREATE TABLE tbBuildInicial(
	idBuildInicial smallint primary key auto_increment,
    idItem1 smallint not null,
    idItem2 smallint,
    idItem3 smallint,
    
    foreign key(idItem1) references tbItem(idItem),
    foreign key(idItem2) references tbItem(idItem),
    foreign key(idItem3) references tbItem(idItem)
);

# TABELA BUILD GERAL
CREATE TABLE tbBuildGeral(
	idBuildGeral smallint primary key auto_increment,
    idItem1 smallint not null,
    idItem2 smallint not null,
    idItem3 smallint not null,
    idItem4 smallint not null,
    idItem5 smallint not null,
    idItem6 smallint not null,
    
    foreign key(idItem1) references tbItem(idItem),
    foreign key(idItem2) references tbItem(idItem),
    foreign key(idItem3) references tbItem(idItem),
    foreign key(idItem4) references tbItem(idItem),
    foreign key(idItem5) references tbItem(idItem),
    foreign key(idItem6) references tbItem(idItem)
);

# TABELA BUILD SITUACIONAL
CREATE TABLE tbBuildSituacional(
	idBuildSituacional smallint primary key auto_increment,
    idItem1 smallint not null,
    idItem2 smallint not null,
    idItem3 smallint,
    
    foreign key(idItem1) references tbItem(idItem),
    foreign key(idItem2) references tbItem(idItem),
    foreign key(idItem3) references tbItem(idItem)
);

# TABELA BUILD PARA CAMPEÃO
CREATE TABLE tbBuild(
	idBuild smallint primary key auto_increment,
    idBuildInicial smallint not null,
    idBuildGeral smallint not null,
    idBuildSituacional smallint not null,
    
    foreign key(idBuildInicial) references tbBuildInicial(idBuildInicial),
    foreign key(idBuildGeral) references tbBuildGeral(idBuildGeral),
    foreign key(idBuildSituacional) references tbBuildSituacional(idBuildSituacional)
);

# TABELA ÁRVORES DE RUNAS
CREATE TABLE tbTree(
	idTree smallint primary key auto_increment,
    nomTree varchar(16) not null,
    keyTree varchar(24) not null
);

INSERT INTO tbTree(nomTree, keyTree)
	values ('Dominação', 'Domination'),
		   ('Inspiração', 'Inspiration'),
		   ('Precisão', 'Precision'),
		   ('Feitiçaria', 'Resolve');

# TABELA RUNAS
CREATE TABLE tbRune(
	idRune smallint primary key auto_increment,
	idTreeRune smallint not null,
    nomRune varchar(32) not null,
    imgRune varchar(32) not null,
    
    foreign key(idTreeRune) references tbTree(idTree)
);

INSERT INTO tbRune(idTreeRune, nomRune, imgRune)
	values (1, 'Eletrocutar', 'Electrocute'),
		   (1, 'Predador', 'Predator'),
		   (1, 'Colheita Sombria', 'DarkHarvest'),
		   (1, 'Chuva de Lâminas', 'HailOfBlades'),
		   (1, 'Golpe Desleal', 'CheapShot'),
		   (1, 'Gosto de Sangue', 'TasteOfBlood'),
		   (1, 'Impacto Repentino', 'SuddenImpact'),
		   (1, 'Sentinela Zumbi', 'ZombieWard'),
		   (1, 'Poro Fantasma', 'GhostPoro'),
		   (1, 'Globos Oculares', 'EyeballCollection'),
		   (1, 'Caçador de Tesouros', 'TreasureHunter'),
		   (1, 'Caça Ardilosa', 'IngeniousHunter'),
		   (1, 'Caça Incansável', 'RelentlessHunter'),
		   (1, 'Caça Suprema', 'UltimateHunter'),
           
		   (2, 'Aprimoramento Glacial', 'GlacialAugment'),
		   (2, 'Livro de Feitiços Deslacrado', 'UnsealedSpellbook'),
		   (2, 'Primeiro Ataque', 'FirstStrike'),
		   (2, 'Flashtração Hextec', 'HextechFlashtraption'),
		   (2, 'Calçados Mágicos', 'MagicalFootwear'),
		   (2, 'Sincronia Perfeita', 'PerfectTiming'),
		   (2, 'Mercado do Futuro', 'FuturesMarket'),
		   (2, 'Pulverizador de Tropas', 'MinionDematerializer'),
		   (2, 'Entrega de Biscoitos', 'BiscuitDelivery'),
		   (2, 'Perspicácia Cósmica', 'CosmicInsight'),
		   (2, 'Velocidade de Aproximação', 'ApproachVelocity'),
		   (2, 'Tônico de Distorção no Tempo', 'TimeWarpTonic'),
           
		   (3, 'Pressione o Ataque', 'PressTheAttack'),
		   (3, 'Ritmo Fatal', 'LethalTempo'),
		   (3, 'Agilidade nos Pés', 'FleetFootwork'),
		   (3, 'Conquistador', 'Conqueror'),
		   (3, 'Cura Excessiva', 'Overheal'),
		   (3, 'Triunfo', 'Triumph'),
		   (3, 'Presença de Espírito', 'PresenceOfMind'),
		   (3, 'Lenda: Espontaneidade', 'LegendAlacrity'),
		   (3, 'Lenda: Tenacidade', 'LegendTenacity'),
		   (3, 'Lenda: Linhagem', 'LegendBloodline'),
		   (3, 'Golpe de Misericórdia', 'CoupDeGrace'),
		   (3, 'Dilacerar', 'CutDown'),
		   (3, 'Até a Morte', 'LastStand'),
           
		   (4, 'Aperto dos Mortos-Vivos', 'GraspOfTheUndying'),
		   (4, 'Pós-choque', 'Aftershock'),
		   (4, 'Guardião', 'Guardian'),
		   (4, 'Demolir', 'Demolish'),
		   (4, 'Fonte da Vida', 'FontOfLife'),
		   (4, 'Golpe de Escudo', 'ShieldBash'),
		   (4, 'Condicionamento', 'Conditioning'),
		   (4, 'Ventos Revigorantes', 'SecondWind'),
		   (4, 'Osso Revestido', 'BonePlating'),
		   (4, 'Crescimento Excessivo', 'Overgrowth'),
		   (4, 'Revitalizar', 'Revitalize'),
		   (4, 'Inabalável', 'Unflinching');

# TABELA ÁRVORE PRIMÁRIA
CREATE TABLE tbPrimTree(
	idPrimTree smallint primary key auto_increment,
    idTree smallint not null,
    idRunePrincipal smallint not null,
    idRunePrim smallint not null,
    idRuneSec smallint not null,
    idRuneTerc smallint not null,
    
    foreign key(idTree) references tbTree(idTree),
    foreign key(idRunePrincipal) references tbRune(idRune),
    foreign key(idRunePrim) references tbRune(idRune),
    foreign key(idRuneSec) references tbRune(idRune),
    foreign key(idRuneTerc) references tbRune(idRune)
);

# TABELA ÁRVORE SECUNDÁRIA
CREATE TABLE tbSecTree(
	idSecTree smallint primary key auto_increment,
    nomTree varchar(16) not null,
    keyTree varchar(24) not null,
    idRunePrim smallint not null,
    idRuneSec smallint not null,
    
    foreign key(idRunePrim) references tbRune(idRune),
    foreign key(idRuneSec) references tbRune(idRune)
);

# TABELA CONJUNTO DE RUNAS PARA O CAMPEÃO
CREATE TABLE tbConjRunes(
	idConjRunes smallint primary key auto_increment,
	idPrimTree smallint not null,
    idSecTree smallint not null,
    
    foreign key(idPrimTree) references tbPrimTree(idPrimTree),
    foreign key(idSecTree) references tbSecTree(idSecTree)
);

# TABELA CAMPEÃO
CREATE TABLE tbChampion(
	idChampion smallint primary key auto_increment,
    nomChampion varchar(36) not null,
    imgChampion varchar(36) not null,
    idPairSpells smallint not null,
    idBuild smallint not null,
    idConjRunes smallint not null,
    
    foreign key(idPairSpells) references tbPairSpells(idPairSpells),
    foreign key(idBuild) references tbBuild(idBuild),
    foreign key(idConjRunes) references tbConjRunes(idConjRunes)
);