version: '3.4'

services:
  leagueofyourlegends_api:
    image: leagueofyourlegendsapi:dev
    container_name: LeagueOfYourLegends_API_1
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "LeagueOfYourLegends_API"
    volumes:
      - C:\Users\mateu\source\repos\LeagueOfYourLegends_API\LeagueOfYourLegends_API:C:\inetpub\wwwroot
      - C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    environment:
      - DEV_ENVIRONMENT=1
      - VBCSCOMPILER_TTL=604800

